version: "3.8"

services:
  app:
    build: .
    container_name: portfolio-app
    ports:
      - "8080:8070"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=default
    
      

